# Generated by Django 5.0.4 on 2024-10-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_category_slug_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
